### ISSUE TITLE
514/515

### ISSUE THREAD

**Issue by yakobie** [SijyKijy/SpaceStation13-Cheat#1]
Hi, I was wondering if anything might of changed with fullbright since the time this was written? I want to begin reversing byond but I do not want to waste time if you know anything about this.

Do you have telegram?

**Comment by SijyKijy** [comment]
¯\\_(ツ)_/¯
If i'm not mistaken this was for 513.
You can install version 513 and start your research from there. Good luck 🥸

**Comment by SijyKijy** [comment]
@yakobie Hey! Discovered this project and post purely by accident.
I hope this information will help you :)

https://www.unknowncheats.me/forum/other-games/516467-syndicate-byond-ss13-cheat-spoofer-2.html#post3952063
